name: just_chat
description: "Just Chat - A simple chat application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP client
  dio: ^5.4.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local storage
  shared_preferences: ^2.2.2

  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
